### ISSUE TITLE
completed projects still gives "Add New Project" message

### ISSUE THREAD

**Issue by RagenS9** [RagensFantabulousIdea/Ensemble#199]
When there are no completed projects in the Completed Projects view, it still gives the instruction to click the "Add New Project" button to get started. Since you worked on this before, can you look and see what's going on there? thank youuuuu!

**Comment by manpreetmondair** [comment]
Yes, I was gone. I used this

                    {location.href.includes('/complete') ? '' : <div className="row">
                        <div className="col-sm-12">
                            <button type="button" className="btn addButton pull-right" onClick={() => browserHistory.push('/projects/new')}>Add New Project</button>
